kind = "api"
previewPath = "/api"
title = "EduFlow Backend"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8082
name = "EduFlow Backend"
paths = ["/api"]

[services.development]
run = "cd ../eduflow-backend && mvn -q spring-boot:run"

[services.production]

[services.production.build]
args = ["bash", "-c", "cd artifacts/eduflow-backend && mvn -q -DskipTests package"]

[services.production.run]
args = ["bash", "-c", "cd artifacts/eduflow-backend && java -jar target/eduflow-backend.jar"]

[services.production.health.startup]
path = "/api/actuator/health"
